// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr8Ut4OB6-Iu4JC4ToGp8W0hBNC2hUAJs',
    appId: '1:77080749785:web:1020c85b7063f9ad3940c8',
    messagingSenderId: '77080749785',
    projectId: 'reels-a60ee',
    authDomain: 'reels-a60ee.firebaseapp.com',
    storageBucket: 'reels-a60ee.firebasestorage.app',
    measurementId: 'G-H5EVWMJVLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm2RALWNRI49TvTWmfFy67jLFB43QLP-8',
    appId: '1:77080749785:android:2f34a41f6851e7403940c8',
    messagingSenderId: '77080749785',
    projectId: 'reels-a60ee',
    storageBucket: 'reels-a60ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkF13_OBT8PpgXtvBWEfu-SWXx7Em4BHc',
    appId: '1:77080749785:ios:14caadf582d32a2a3940c8',
    messagingSenderId: '77080749785',
    projectId: 'reels-a60ee',
    storageBucket: 'reels-a60ee.firebasestorage.app',
    iosBundleId: 'com.example.reelsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkF13_OBT8PpgXtvBWEfu-SWXx7Em4BHc',
    appId: '1:77080749785:ios:14caadf582d32a2a3940c8',
    messagingSenderId: '77080749785',
    projectId: 'reels-a60ee',
    storageBucket: 'reels-a60ee.firebasestorage.app',
    iosBundleId: 'com.example.reelsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr8Ut4OB6-Iu4JC4ToGp8W0hBNC2hUAJs',
    appId: '1:77080749785:web:8256fbbebd18b9463940c8',
    messagingSenderId: '77080749785',
    projectId: 'reels-a60ee',
    authDomain: 'reels-a60ee.firebaseapp.com',
    storageBucket: 'reels-a60ee.firebasestorage.app',
    measurementId: 'G-862WMJWX0T',
  );

}